// Views
// -----
// Do not edit this file. If you would like to change the views, use `urza [create|remove] view [--route ":some/:path"] [--raw] <viewname>`
// See README for more info.
var viewObject = {
  'lib/views/main' : '*path'
};
// do not edit this line.
define(['lib/views/main'],function(){ return { views : arguments, routes : viewObject } });